[package]
edition = "2018"
license = "Apache-2.0/MIT"
name = "macro_common"
version = "0.1.0"

[dependencies]
pmutil = "0.5.1"
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
features = ["derive", "visit", "parsing", "full", "printing", "extra-traits"]
version = "=1.0.65"
