[package]
description = "Visitors for ecmascript nodes which works on stable rustc"
edition = "2018"
license = "Apache-2.0/MIT"
name = "ecma_visit"
version = "0.1.0"

[dependencies]
ast = {version = "0.1.0", path = "../ast"}
global_common = {version = "0.1.0", path = "../common"}
global_visit = {version = "0.1.0", path = "../../visit"}
num-bigint = {version = "0.2", features = ["serde"]}
swc_atoms = "0.2"
