[package]
name = "compiler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = {path = "../ast"}
ahash = "0.7.6"
bitflags = "1.3"
global_common = {path = "../common"}
ast_convert = {path = "../../macros/ast_convert"}
visit2 = {path = "../../macros/visit2"}
num-bigint = {version = "0.2", features = ["serde"]}
swc_atoms = "0.2"
index = {path = "../index"}
once_cell = "1.10.0"
regex = "1"

[dev-dependencies]
testing = {path = "../../testing"}
parser = {path = "../parser"}