[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = { workspace = true }
bitflags = { workspace = true }
indexmap = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
petgraph = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }

ast = { path = "../ast" }
visit = { path = "../visit" }
common = { path = "../common" }
index = { path = "../index" }

[dev-dependencies]
criterion = { workspace = true }

codegen = { path = "../codegen" }
custom_alloc = { path = "../custom_alloc" }
parser = { path = "../parser" }
testing = { path = "../testing" }

[[bench]]
name = "bench_main"
harness = false
