[workspace]
members = ["crates/*"]
resolver = "1"

[workspace.dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.86"
arrayvec = "0.7"
atty = "0.2"
bitflags = "2.6"
criterion = "0.5"
difference = "2.0.0"
hashbrown = { version = "0.14.5", default-features = false }
indexmap = "2.2.6"
mimalloc = "0.1"
num-bigint = "0.4.8"
num-traits = "0.2.18"
paste = "1.0.15"
petgraph = "0.6.5"
pretty_assertions = "1.4.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
rustc-hash = "1.1.0"
serde = "1.0.204"
serde_json = "1.0.120"
serde-wasm-bindgen = "0.6.5"
sourcemap = "6.2"
syn = "2.0.72"
termcolor = "1.0"
unicode-width = "0.1.4"
unicode-id-start = "1.4.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
