[workspace]
members = [
    "crates/*",
    "crates/ts/diagnostics",
    "macros/*",
    "xtask"
]

[profile.release]
codegen-units = 1
lto = true
debug = true

[profile.bench]
codegen-units = 1
debug = true