[package]
name = "ast"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
num-bigint = { workspace = true }
unicode-id-start = { workspace = true }

atoms = { path = "../atoms" }
clone_node = { path = "../clone_node" }
global_common = { path = "../common" }
index = { path = "../index" }
node_id = { path = "../node_id" }
