[package]
name = "ast"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true, features = ["serde"] }
hashbrown = { workspace = true, features = ["inline-more"] }
paste = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
unicode-id-start = { workspace = true }

big_int = { path = "../big_int" }
clone_node = { path = "../clone_node" }
common = { path = "../common" }
index = { path = "../index" }
node_eq = { path = "../node_eq" }
node_id = { path = "../node_id" }
