[package]
name = "ast"
version = "0.1.0"
authors = ["Campbell <campbell.wass@gmail.com>"]
edition = "2018"

[dependencies]
global_common = {version = "0.1.0", path = "../common"}
index = {path = "../index"}
num-bigint = {version = "0.2"}
string_enum = {version = "0.1.0", path = "../../macros/string_enum"}
swc_atoms = "0.2.6"
