[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

ast = { path = "../ast" }
codegen = { path = "../codegen" }
compiler = { path = "../compiler" }
custom_alloc = { path = "../custom_alloc" }
common = { path = "../common", features = ["tty-emitter", "sourcemap"] }
parser = { path = "../parser" }
