[package]
name = "cli"
version = "0.1.0"
authors = ["Campbell <campbell.wass@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
global_common = {version = "0.1.0", path = "../common"}
parser = {version = "0.1.0", path = "../parser"}