[package]
name = "parser"
version = "0.1.0"
authors = ["Campbell <campbell.wass@gmail.com>"]
edition = "2018"

[dependencies]
ast = {version = "0.1.0", path = "../ast"}
either = "1.6.1"
enum_kind = "0.2.1"
global_common = {version = "0.1.0", path = "../common"}
num-bigint = "0.2"
string_enum = {version = "0.1.0", path = "../../macros/string_enum"}
swc_atoms = "0.2.6"
unicode-xid = "0.2.1"
