[package]
name = "parser"
version = "0.1.0"
authors = ["Campbell <campbell.wass@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
either = "1.6.1"
num-bigint = "0.4.6"
serde = {version = "1", features = ["derive"]}
unicode-xid = "0.2.1"

ast = {path = "../ast"}
ast_node = {path = "../../macros/ast_node"}
atoms = {path = "../atoms"}
ecma_visit = {path = "../visit"}
global_common = {path = "../common"}
string_enum = {path = "../../macros/string_enum"}

[dev-dependencies]
criterion = "0.3"
serde_json = "1"

testing = {path = "../../testing"}
transform_testing = { path = "../transform_testing" }

[[bench]]
name = "bench_main"
harness = false