[package]
name = "parser"
version = "0.1.0"
authors = ["Campbell <campbell.wass@gmail.com>"]
edition = "2018"

[dependencies]
unicode-xid = "0.2.1"
from_variant = "0.1.3"
enum_kind = "0.2.1"
num-bigint = "0.2"
global_common = {path = "../common"}
string_enum = {version = "0.1.0", path = "../../macros/string_enum"}
either = "1.6.1"
swc_atoms = "0.2.6"
