[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
bitflags = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }

ast = { path = "../ast" }
big_int = { path = "../big_int" }
common = { path = "../common" }

[dev-dependencies]
criterion = { workspace = true }
serde_json = { workspace = true }

custom_alloc = { path = "../custom_alloc" }
visit = { path = "../visit" }
testing = { path = "../testing" }

[[bench]]
name = "bench_main"
harness = false
