[package]
name = "parser"
version = "0.1.0"
authors = ["Campbell <campbell.wass@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
ast = {version = "0.1.0", path = "../ast"}
ecma_visit = {version = "0.1.0", path = "../visit"}
either = "1.6.1"
enum_kind = "0.2.1"
global_common = {version = "0.1.0", path = "../common"}
num-bigint = "0.2"
serde = {version = "1", features = ["derive"]}
string_enum = {version = "0.1.0", path = "../../macros/string_enum"}
swc_atoms = "0.2.6"
unicode-xid = "0.2.1"

[dev-dependencies]
criterion = "0.3"
serde_json = "1"
testing = {version = "0.1.0", path = "../../testing"}

[[bench]]
name = "bench_main"
harness = false