[package]
edition = "2024"
name = "transform_testing"
version = "0.1.0"

[dependencies]
ansi_term = { workspace = true }

ast = { path = "../ast" }
codegen = { path = "../codegen" }
visit = { path = "../visit" }
common = { path = "../common", features = ["sourcemap"] }
parser = { path = "../parser" }
testing = { path = "../testing" }
