[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
tty-emitter = ["atty", "termcolor"]

[dependencies]
atty = { workspace = true, optional = true }
cfg-if = { workspace = true }
scoped-tls = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sourcemap = { workspace = true, optional = true }
termcolor = { workspace = true, optional = true }
unicode-width = { workspace = true }
