[package]
edition = "2024"
include = ["Cargo.toml", "src/**/*.rs"]
license = "Apache-2.0/MIT"
name = "codegen"
repository = "https://github.com/swc-project/swc.git"
version = "0.1.0"

[dependencies]
bitflags = { workspace = true }

ast = { path = "../ast" }
global_common = { path = "../common" }

[dev-dependencies]
custom_alloc = { path = "../custom_alloc" }
global_common = { path = "../common", features = ["sourcemap"] }
parser = { path = "../parser" }
testing = { path = "../../testing" }
