[package]
edition = "2024"
name = "codegen"
version = "0.1.0"

[dependencies]
bitflags = { workspace = true }

ast = { path = "../ast" }
common = { path = "../common" }

[dev-dependencies]
custom_alloc = { path = "../custom_alloc" }
common = { path = "../common", features = ["sourcemap"] }
parser = { path = "../parser" }
testing = { path = "../testing" }
